name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        target:
          - alpine
          - debian
        include:
          - target: alpine
            platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8'
            tag-latest: false
            tag-semver: |
              v{{version}}-alpine
            tag-custom: alpine
            tag-custom-only: false
          - target: debian
            platforms: 'linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8'
            tag-latest: true
            tag-semver: |
              v{{version}}-debian
              v{{version}}
            tag-custom: debian
            tag-custom-only: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKERHUB_IMAGE }}
          tag-latest: ${{ matrix.tag-latest }}
          tag-semver: ${{ matrix.tag-semver }}
          tag-custom: ${{ matrix.tag-custom }}
          tag-custom-only: ${{ matrix.tag-custom-only }}
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.target }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.target }}-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.target }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
